name: Create Random Chinese From Unicode

on: push

jobs:
  generate-unicode:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create Random Chinese
        id: createchinese
        uses: konjoinfinity/random-unicode-text-generator@v1.0.0
        with:
          numOfChars: "1000"
          startRange: "0x4e00"
          endRange: "0x9fff"

      - name: Show Output
        run: |
          echo ${{ steps.createchinese.outputs.output }}
