# name: Automatic pull request review
# on: 
#   pull_request:
#     types: [ labeled ]
    
# jobs:
#   automate-pullrequest-submit:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.label.name == 'Submit' }}
#     steps:
    
#       - name: Get Data
#         id: getdata
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://ciprand.p3p.repl.co/api?len=150&count=1")
#           echo "::set-output name=data::$(echo $RESPONSE | jq -r '.Strings[0]')"
          
#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
#           message: |
#             ${{ steps.getdata.outputs.data }}
#           reactions: eyes, rocket, +1, heart
          
#       - name: Get Inspiration
#         id: getinspiration
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://api.fisenko.net/v1/quotes/en/random")
#           echo "::set-output name=text::$(echo $RESPONSE | jq -r '.text')"
#           echo "::set-output name=author::$(echo $RESPONSE | jq -r '.author.name')"
          
#       - name: Wait
#         id: wait
#         run: |
#           sleep 5
          
#       - name: Approve pull request
#         if: github.actor == 'wesleyscholl'
#         uses: andrewmusgrave/automatic-pull-request-review@0.0.5
#         with:
#           repo-token: ${{ secrets.GITHUB_TOKEN }}
#           event: APPROVE
#           body: ${{ steps.getinspiration.outputs.text }} - ${{ steps.getinspiration.outputs.author }}
          
#       - name: Wait Again
#         id: waitagain
#         run: |
#           sleep 5
          
#       - name: Merge
#         uses: KeisukeYamashita/auto-pull-request-merge@v1
#         with:
#           intervalSeconds: 5
#           timeoutSeconds: 30
#           comment: "Merged"
#           token: ${{ secrets.GH_TOKEN }}

#   automate-pullrequest-review:
#     runs-on: ubuntu-latest
#     if: ${{ github.event.label.name == 'Review' }}
#     steps:

#       - name: Get Trivia
#         id: gettrivia
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://ciprand.p3p.repl.co/api?len=100&count=1")
#           echo "::set-output name=data::$(echo $RESPONSE | jq -r '.Strings[0]')"

#       - name: Wait1
#         id: wait1
#         run: |
#           sleep 5
        
#       - name: Comment on pull request
#         uses: andrewmusgrave/automatic-pull-request-review@0.0.5
#         with:
#           repo-token: ${{ secrets.GH_TOKEN }}
#           event: COMMENT
#           body: ${{ steps.gettrivia.outputs.data }}

#       - name: Get Data
#         id: getdata
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://ciprand.p3p.repl.co/api?len=150&count=1")
#           echo "::set-output name=data::$(echo $RESPONSE | jq -r '.Strings[0]')"
          
#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           GITHUB_TOKEN: ${{ github.token }}
#           message: |
#             ${{ steps.getdata.outputs.data }}
#           reactions: +1, heart
            
#       - name: Get Inspiration
#         id: getinspiration
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://api.fisenko.net/v1/quotes/en/random")
#           echo "::set-output name=text::$(echo $RESPONSE | jq -r '.text')"
#           echo "::set-output name=author::$(echo $RESPONSE | jq -r '.author.name')"

#       - name: Wait2
#         id: wait2
#         run: |
#           sleep 5
        
#       - name: Approve pull request
#         uses: andrewmusgrave/automatic-pull-request-review@0.0.5
#         with:
#           repo-token: ${{ secrets.GH_TOKEN }}
#           event: APPROVE
#           body: ${{ steps.getinspiration.outputs.text }} - ${{ steps.getinspiration.outputs.author }}

#       - name: Get Data 1
#         id: getdata1
#         run: |
#           sleep 5
#           RESPONSE=$(curl -s "https://ciprand.p3p.repl.co/api?len=75&count=1")
#           echo "::set-output name=data::$(echo $RESPONSE | jq -r '.Strings[0]')"
          
#       - name: Comment PR
#         uses: thollander/actions-comment-pull-request@v2
#         with:
#           GITHUB_TOKEN: ${{ github.token }}
#           message: |
#             ${{ steps.getdata1.outputs.data }}
#           reactions: +1, -1, laugh, confused, heart, hooray, rocket, eyes

#       - name: Wait Again
#         id: waitagain
#         run: |
#           sleep 5
          
#       - name: Merge
#         uses: KeisukeYamashita/auto-pull-request-merge@v1
#         with:
#           intervalSeconds: 5
#           timeoutSeconds: 30
#           comment: "Merged"
#           token: ${{ secrets.GH_TOKEN }}
  
